In [13]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from matplotlib import style
style.use('dark_background')
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [4]:
data = pd.read_csv("data.csv")

In [5]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
import math
median_bedrooms = math.floor(data.bedrooms.median())
median_bedrooms

3

In [11]:
data.bedrooms = data.bedrooms.fillna(median_bedrooms)
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [16]:
model = LinearRegression()
model.fit(data[['area','bedrooms','age']],data.price)

LinearRegression()

In [19]:
model.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [23]:
model.intercept_

383724.99999999994

In [20]:
model.predict([[3000,3,40]])

array([444400.])

In [21]:
model.predict([[2500,4,5]])

array([588625.])

In [22]:
data.describe()

area  bedrooms       age          price
count     5.000000  5.000000   5.00000       5.000000
mean   3280.000000  3.600000  18.20000  616000.000000
std     540.370243  0.894427   8.01249   83919.604384
min    2600.000000  3.000000   8.00000  550000.000000
25%    3000.000000  3.000000  15.00000  565000.000000
50%    3200.000000  3.000000  18.00000  595000.000000
75%    3600.000000  4.000000  20.00000  610000.000000
max    4000.000000  5.000000  30.00000  760000.000000